### ISSUE TITLE
不能上线使用，调用的腾讯地图服务是http的，小程序合法域名配置只能https

### ISSUE THREAD

**Issue by AJaylin** [BeijiYang/citySelector#3]
rt

**Comment by BeijiYang** [comment]
@AJaylin 

>入门指南
WebService API
HTTP数据接口，适用于服务端或任意支持HTTP协议的环境，
目前腾讯地图WebService API已全面支持HTTPS协议，使用时只需修改协议头为`https://`即可

请先仔细阅读官方文档的[入门指南](http://lbs.qq.com/guides/startup.html)，挺详细的。
如有帮助请 star
(•̀ᴗ•́)و ̑̑
