### ISSUE TITLE
非常赞的组件，我集成到了mpvue框架上

### ISSUE THREAD

**Issue by originalix** [BeijiYang/citySelector#4]
看到作者的小组件，觉得非常实用。不过我的项目是基于mpvue上的，我花了一点时间在mpvue上改写了。

项目地址：https://github.com/originalix/citySelector

希望大佬方便的话也能挂在readme里 方便使用mpvue的同学们

**Comment by BeijiYang** [comment]
哈，好的。感谢认可。我更新一下 readme。
